// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilityEnum string

const (
	AvailabilityEnumFullTime AvailabilityEnum = "full_time"
	AvailabilityEnumPartTime AvailabilityEnum = "part_time"
	AvailabilityEnumAsNeeded AvailabilityEnum = "as_needed"
)

func (e *AvailabilityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AvailabilityEnum(s)
	case string:
		*e = AvailabilityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AvailabilityEnum: %T", src)
	}
	return nil
}

type NullAvailabilityEnum struct {
	AvailabilityEnum AvailabilityEnum `json:"availability_enum"`
	Valid            bool             `json:"valid"` // Valid is true if AvailabilityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAvailabilityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AvailabilityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AvailabilityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAvailabilityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AvailabilityEnum), nil
}

type BudgetTypeEnum string

const (
	BudgetTypeEnumFixed  BudgetTypeEnum = "fixed"
	BudgetTypeEnumHourly BudgetTypeEnum = "hourly"
)

func (e *BudgetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BudgetTypeEnum(s)
	case string:
		*e = BudgetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BudgetTypeEnum: %T", src)
	}
	return nil
}

type NullBudgetTypeEnum struct {
	BudgetTypeEnum BudgetTypeEnum `json:"budget_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if BudgetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBudgetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BudgetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BudgetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBudgetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BudgetTypeEnum), nil
}

type ContractStatusEnum string

const (
	ContractStatusEnumPending   ContractStatusEnum = "pending"
	ContractStatusEnumActive    ContractStatusEnum = "active"
	ContractStatusEnumCompleted ContractStatusEnum = "completed"
	ContractStatusEnumCancelled ContractStatusEnum = "cancelled"
	ContractStatusEnumDisputed  ContractStatusEnum = "disputed"
	ContractStatusEnumPaused    ContractStatusEnum = "paused"
)

func (e *ContractStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractStatusEnum(s)
	case string:
		*e = ContractStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractStatusEnum: %T", src)
	}
	return nil
}

type NullContractStatusEnum struct {
	ContractStatusEnum ContractStatusEnum `json:"contract_status_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ContractStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ContractStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractStatusEnum), nil
}

type DisputeStatusEnum string

const (
	DisputeStatusEnumOpen     DisputeStatusEnum = "open"
	DisputeStatusEnumInReview DisputeStatusEnum = "in_review"
	DisputeStatusEnumResolved DisputeStatusEnum = "resolved"
	DisputeStatusEnumClosed   DisputeStatusEnum = "closed"
)

func (e *DisputeStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeStatusEnum(s)
	case string:
		*e = DisputeStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeStatusEnum: %T", src)
	}
	return nil
}

type NullDisputeStatusEnum struct {
	DisputeStatusEnum DisputeStatusEnum `json:"dispute_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if DisputeStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeStatusEnum), nil
}

type DisputeTypeEnum string

const (
	DisputeTypeEnumPayment       DisputeTypeEnum = "payment"
	DisputeTypeEnumQuality       DisputeTypeEnum = "quality"
	DisputeTypeEnumCommunication DisputeTypeEnum = "communication"
	DisputeTypeEnumScope         DisputeTypeEnum = "scope"
	DisputeTypeEnumOther         DisputeTypeEnum = "other"
)

func (e *DisputeTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeTypeEnum(s)
	case string:
		*e = DisputeTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeTypeEnum: %T", src)
	}
	return nil
}

type NullDisputeTypeEnum struct {
	DisputeTypeEnum DisputeTypeEnum `json:"dispute_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if DisputeTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeTypeEnum), nil
}

type ExperienceLevelEnum string

const (
	ExperienceLevelEnumBeginner     ExperienceLevelEnum = "beginner"
	ExperienceLevelEnumIntermediate ExperienceLevelEnum = "intermediate"
	ExperienceLevelEnumExpert       ExperienceLevelEnum = "expert"
)

func (e *ExperienceLevelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExperienceLevelEnum(s)
	case string:
		*e = ExperienceLevelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ExperienceLevelEnum: %T", src)
	}
	return nil
}

type NullExperienceLevelEnum struct {
	ExperienceLevelEnum ExperienceLevelEnum `json:"experience_level_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ExperienceLevelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExperienceLevelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ExperienceLevelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExperienceLevelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExperienceLevelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExperienceLevelEnum), nil
}

type JobStatusEnum string

const (
	JobStatusEnumDraft      JobStatusEnum = "draft"
	JobStatusEnumOpen       JobStatusEnum = "open"
	JobStatusEnumInProgress JobStatusEnum = "in_progress"
	JobStatusEnumCompleted  JobStatusEnum = "completed"
	JobStatusEnumCancelled  JobStatusEnum = "cancelled"
	JobStatusEnumPaused     JobStatusEnum = "paused"
)

func (e *JobStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusEnum(s)
	case string:
		*e = JobStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusEnum: %T", src)
	}
	return nil
}

type NullJobStatusEnum struct {
	JobStatusEnum JobStatusEnum `json:"job_status_enum"`
	Valid         bool          `json:"valid"` // Valid is true if JobStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatusEnum), nil
}

type LocationTypeEnum string

const (
	LocationTypeEnumRemote LocationTypeEnum = "remote"
	LocationTypeEnumOnSite LocationTypeEnum = "on_site"
	LocationTypeEnumHybrid LocationTypeEnum = "hybrid"
)

func (e *LocationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationTypeEnum(s)
	case string:
		*e = LocationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationTypeEnum: %T", src)
	}
	return nil
}

type NullLocationTypeEnum struct {
	LocationTypeEnum LocationTypeEnum `json:"location_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if LocationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LocationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationTypeEnum), nil
}

type MessageTypeEnum string

const (
	MessageTypeEnumText   MessageTypeEnum = "text"
	MessageTypeEnumFile   MessageTypeEnum = "file"
	MessageTypeEnumImage  MessageTypeEnum = "image"
	MessageTypeEnumSystem MessageTypeEnum = "system"
)

func (e *MessageTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageTypeEnum(s)
	case string:
		*e = MessageTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageTypeEnum: %T", src)
	}
	return nil
}

type NullMessageTypeEnum struct {
	MessageTypeEnum MessageTypeEnum `json:"message_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if MessageTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MessageTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageTypeEnum), nil
}

type MilestoneStatusEnum string

const (
	MilestoneStatusEnumPending   MilestoneStatusEnum = "pending"
	MilestoneStatusEnumSubmitted MilestoneStatusEnum = "submitted"
	MilestoneStatusEnumApproved  MilestoneStatusEnum = "approved"
	MilestoneStatusEnumRejected  MilestoneStatusEnum = "rejected"
	MilestoneStatusEnumPaid      MilestoneStatusEnum = "paid"
)

func (e *MilestoneStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MilestoneStatusEnum(s)
	case string:
		*e = MilestoneStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MilestoneStatusEnum: %T", src)
	}
	return nil
}

type NullMilestoneStatusEnum struct {
	MilestoneStatusEnum MilestoneStatusEnum `json:"milestone_status_enum"`
	Valid               bool                `json:"valid"` // Valid is true if MilestoneStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMilestoneStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MilestoneStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MilestoneStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMilestoneStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MilestoneStatusEnum), nil
}

type NotificationTypeEnum string

const (
	NotificationTypeEnumJobPosted          NotificationTypeEnum = "job_posted"
	NotificationTypeEnumProposalReceived   NotificationTypeEnum = "proposal_received"
	NotificationTypeEnumProposalAccepted   NotificationTypeEnum = "proposal_accepted"
	NotificationTypeEnumProposalRejected   NotificationTypeEnum = "proposal_rejected"
	NotificationTypeEnumContractSigned     NotificationTypeEnum = "contract_signed"
	NotificationTypeEnumMilestoneSubmitted NotificationTypeEnum = "milestone_submitted"
	NotificationTypeEnumMilestoneApproved  NotificationTypeEnum = "milestone_approved"
	NotificationTypeEnumPaymentReceived    NotificationTypeEnum = "payment_received"
	NotificationTypeEnumReviewReceived     NotificationTypeEnum = "review_received"
	NotificationTypeEnumMessageReceived    NotificationTypeEnum = "message_received"
	NotificationTypeEnumSystem             NotificationTypeEnum = "system"
)

func (e *NotificationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeEnum(s)
	case string:
		*e = NotificationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeEnum: %T", src)
	}
	return nil
}

type NullNotificationTypeEnum struct {
	NotificationTypeEnum NotificationTypeEnum `json:"notification_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTypeEnum), nil
}

type PaymentMethodEnum string

const (
	PaymentMethodEnumCreditCard   PaymentMethodEnum = "credit_card"
	PaymentMethodEnumPaypal       PaymentMethodEnum = "paypal"
	PaymentMethodEnumBankTransfer PaymentMethodEnum = "bank_transfer"
	PaymentMethodEnumWallet       PaymentMethodEnum = "wallet"
)

func (e *PaymentMethodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodEnum(s)
	case string:
		*e = PaymentMethodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodEnum: %T", src)
	}
	return nil
}

type NullPaymentMethodEnum struct {
	PaymentMethodEnum PaymentMethodEnum `json:"payment_method_enum"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentMethodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodEnum), nil
}

type PaymentTermsEnum string

const (
	PaymentTermsEnumMilestone  PaymentTermsEnum = "milestone"
	PaymentTermsEnumHourly     PaymentTermsEnum = "hourly"
	PaymentTermsEnumCompletion PaymentTermsEnum = "completion"
	PaymentTermsEnumWeekly     PaymentTermsEnum = "weekly"
)

func (e *PaymentTermsEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentTermsEnum(s)
	case string:
		*e = PaymentTermsEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentTermsEnum: %T", src)
	}
	return nil
}

type NullPaymentTermsEnum struct {
	PaymentTermsEnum PaymentTermsEnum `json:"payment_terms_enum"`
	Valid            bool             `json:"valid"` // Valid is true if PaymentTermsEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentTermsEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentTermsEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentTermsEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentTermsEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentTermsEnum), nil
}

type ProficiencyLevelEnum string

const (
	ProficiencyLevelEnumBeginner     ProficiencyLevelEnum = "beginner"
	ProficiencyLevelEnumIntermediate ProficiencyLevelEnum = "intermediate"
	ProficiencyLevelEnumAdvanced     ProficiencyLevelEnum = "advanced"
	ProficiencyLevelEnumExpert       ProficiencyLevelEnum = "expert"
)

func (e *ProficiencyLevelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProficiencyLevelEnum(s)
	case string:
		*e = ProficiencyLevelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProficiencyLevelEnum: %T", src)
	}
	return nil
}

type NullProficiencyLevelEnum struct {
	ProficiencyLevelEnum ProficiencyLevelEnum `json:"proficiency_level_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if ProficiencyLevelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProficiencyLevelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProficiencyLevelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProficiencyLevelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProficiencyLevelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProficiencyLevelEnum), nil
}

type ProjectDurationEnum string

const (
	ProjectDurationEnumLessThanWeek    ProjectDurationEnum = "less_than_week"
	ProjectDurationEnum1To4Weeks       ProjectDurationEnum = "1_to_4_weeks"
	ProjectDurationEnum1To3Months      ProjectDurationEnum = "1_to_3_months"
	ProjectDurationEnum3To6Months      ProjectDurationEnum = "3_to_6_months"
	ProjectDurationEnumMoreThan6Months ProjectDurationEnum = "more_than_6_months"
)

func (e *ProjectDurationEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectDurationEnum(s)
	case string:
		*e = ProjectDurationEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectDurationEnum: %T", src)
	}
	return nil
}

type NullProjectDurationEnum struct {
	ProjectDurationEnum ProjectDurationEnum `json:"project_duration_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ProjectDurationEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectDurationEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectDurationEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectDurationEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectDurationEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectDurationEnum), nil
}

type ProposalStatusEnum string

const (
	ProposalStatusEnumPending     ProposalStatusEnum = "pending"
	ProposalStatusEnumShortlisted ProposalStatusEnum = "shortlisted"
	ProposalStatusEnumAccepted    ProposalStatusEnum = "accepted"
	ProposalStatusEnumRejected    ProposalStatusEnum = "rejected"
	ProposalStatusEnumWithdrawn   ProposalStatusEnum = "withdrawn"
)

func (e *ProposalStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProposalStatusEnum(s)
	case string:
		*e = ProposalStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProposalStatusEnum: %T", src)
	}
	return nil
}

type NullProposalStatusEnum struct {
	ProposalStatusEnum ProposalStatusEnum `json:"proposal_status_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ProposalStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProposalStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProposalStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProposalStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProposalStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProposalStatusEnum), nil
}

type RateTypeEnum string

const (
	RateTypeEnumFixed  RateTypeEnum = "fixed"
	RateTypeEnumHourly RateTypeEnum = "hourly"
)

func (e *RateTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateTypeEnum(s)
	case string:
		*e = RateTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RateTypeEnum: %T", src)
	}
	return nil
}

type NullRateTypeEnum struct {
	RateTypeEnum RateTypeEnum `json:"rate_type_enum"`
	Valid        bool         `json:"valid"` // Valid is true if RateTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RateTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateTypeEnum), nil
}

type ReviewStatusEnum string

const (
	ReviewStatusEnumPending   ReviewStatusEnum = "pending"
	ReviewStatusEnumPublished ReviewStatusEnum = "published"
	ReviewStatusEnumDisputed  ReviewStatusEnum = "disputed"
	ReviewStatusEnumRemoved   ReviewStatusEnum = "removed"
)

func (e *ReviewStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatusEnum(s)
	case string:
		*e = ReviewStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatusEnum: %T", src)
	}
	return nil
}

type NullReviewStatusEnum struct {
	ReviewStatusEnum ReviewStatusEnum `json:"review_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ReviewStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatusEnum), nil
}

type StatusEnum string

const (
	StatusEnumActive      StatusEnum = "active"
	StatusEnumSuspended   StatusEnum = "suspended"
	StatusEnumDeactivated StatusEnum = "deactivated"
)

func (e *StatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusEnum(s)
	case string:
		*e = StatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusEnum: %T", src)
	}
	return nil
}

type NullStatusEnum struct {
	StatusEnum StatusEnum `json:"status_enum"`
	Valid      bool       `json:"valid"` // Valid is true if StatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusEnum), nil
}

type TimeLogStatusEnum string

const (
	TimeLogStatusEnumRunning  TimeLogStatusEnum = "running"
	TimeLogStatusEnumStopped  TimeLogStatusEnum = "stopped"
	TimeLogStatusEnumApproved TimeLogStatusEnum = "approved"
	TimeLogStatusEnumRejected TimeLogStatusEnum = "rejected"
)

func (e *TimeLogStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeLogStatusEnum(s)
	case string:
		*e = TimeLogStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeLogStatusEnum: %T", src)
	}
	return nil
}

type NullTimeLogStatusEnum struct {
	TimeLogStatusEnum TimeLogStatusEnum `json:"time_log_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if TimeLogStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeLogStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TimeLogStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeLogStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeLogStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeLogStatusEnum), nil
}

type TransactionStatusEnum string

const (
	TransactionStatusEnumPending    TransactionStatusEnum = "pending"
	TransactionStatusEnumProcessing TransactionStatusEnum = "processing"
	TransactionStatusEnumCompleted  TransactionStatusEnum = "completed"
	TransactionStatusEnumFailed     TransactionStatusEnum = "failed"
	TransactionStatusEnumCancelled  TransactionStatusEnum = "cancelled"
	TransactionStatusEnumRefunded   TransactionStatusEnum = "refunded"
)

func (e *TransactionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatusEnum(s)
	case string:
		*e = TransactionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatusEnum: %T", src)
	}
	return nil
}

type NullTransactionStatusEnum struct {
	TransactionStatusEnum TransactionStatusEnum `json:"transaction_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if TransactionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatusEnum), nil
}

type TransactionTypeEnum string

const (
	TransactionTypeEnumPayment TransactionTypeEnum = "payment"
	TransactionTypeEnumRefund  TransactionTypeEnum = "refund"
	TransactionTypeEnumBonus   TransactionTypeEnum = "bonus"
	TransactionTypeEnumPenalty TransactionTypeEnum = "penalty"
)

func (e *TransactionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionTypeEnum(s)
	case string:
		*e = TransactionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionTypeEnum: %T", src)
	}
	return nil
}

type NullTransactionTypeEnum struct {
	TransactionTypeEnum TransactionTypeEnum `json:"transaction_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if TransactionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionTypeEnum), nil
}

type UrgencyEnum string

const (
	UrgencyEnumLow    UrgencyEnum = "low"
	UrgencyEnumMedium UrgencyEnum = "medium"
	UrgencyEnumHigh   UrgencyEnum = "high"
	UrgencyEnumUrgent UrgencyEnum = "urgent"
)

func (e *UrgencyEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrgencyEnum(s)
	case string:
		*e = UrgencyEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UrgencyEnum: %T", src)
	}
	return nil
}

type NullUrgencyEnum struct {
	UrgencyEnum UrgencyEnum `json:"urgency_enum"`
	Valid       bool        `json:"valid"` // Valid is true if UrgencyEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrgencyEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UrgencyEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrgencyEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrgencyEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrgencyEnum), nil
}

type UserTypeEnum string

const (
	UserTypeEnumClient     UserTypeEnum = "client"
	UserTypeEnumFreelancer UserTypeEnum = "freelancer"
	UserTypeEnumBoth       UserTypeEnum = "both"
)

func (e *UserTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserTypeEnum(s)
	case string:
		*e = UserTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserTypeEnum: %T", src)
	}
	return nil
}

type NullUserTypeEnum struct {
	UserTypeEnum UserTypeEnum `json:"user_type_enum"`
	Valid        bool         `json:"valid"` // Valid is true if UserTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserTypeEnum), nil
}

type VisibilityEnum string

const (
	VisibilityEnumPublic      VisibilityEnum = "public"
	VisibilityEnumPrivate     VisibilityEnum = "private"
	VisibilityEnumInvitedOnly VisibilityEnum = "invited_only"
)

func (e *VisibilityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisibilityEnum(s)
	case string:
		*e = VisibilityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for VisibilityEnum: %T", src)
	}
	return nil
}

type NullVisibilityEnum struct {
	VisibilityEnum VisibilityEnum `json:"visibility_enum"`
	Valid          bool           `json:"valid"` // Valid is true if VisibilityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibilityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.VisibilityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisibilityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibilityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisibilityEnum), nil
}

type Category struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	IconUrl     pgtype.Text        `db:"icon_url" json:"icon_url"`
	ParentID    pgtype.Int8        `db:"parent_id" json:"parent_id"`
	IsActive    pgtype.Bool        `db:"is_active" json:"is_active"`
	SortOrder   pgtype.Int4        `db:"sort_order" json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Contract struct {
	ID                   int64                  `db:"id" json:"id"`
	JobID                int64                  `db:"job_id" json:"job_id"`
	ClientID             int64                  `db:"client_id" json:"client_id"`
	FreelancerID         int64                  `db:"freelancer_id" json:"freelancer_id"`
	ProposalID           pgtype.Int8            `db:"proposal_id" json:"proposal_id"`
	Title                string                 `db:"title" json:"title"`
	Description          pgtype.Text            `db:"description" json:"description"`
	ContractType         RateTypeEnum           `db:"contract_type" json:"contract_type"`
	TotalAmount          pgtype.Numeric         `db:"total_amount" json:"total_amount"`
	HourlyRate           pgtype.Numeric         `db:"hourly_rate" json:"hourly_rate"`
	EstimatedHours       pgtype.Int4            `db:"estimated_hours" json:"estimated_hours"`
	StartDate            pgtype.Date            `db:"start_date" json:"start_date"`
	EndDate              pgtype.Date            `db:"end_date" json:"end_date"`
	Status               NullContractStatusEnum `db:"status" json:"status"`
	TermsAndConditions   pgtype.Text            `db:"terms_and_conditions" json:"terms_and_conditions"`
	PaymentTerms         NullPaymentTermsEnum   `db:"payment_terms" json:"payment_terms"`
	CreatedAt            pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
	SignedByClientAt     pgtype.Timestamptz     `db:"signed_by_client_at" json:"signed_by_client_at"`
	SignedByFreelancerAt pgtype.Timestamptz     `db:"signed_by_freelancer_at" json:"signed_by_freelancer_at"`
	CompletedAt          pgtype.Timestamptz     `db:"completed_at" json:"completed_at"`
}

type Dispute struct {
	ID             int64                 `db:"id" json:"id"`
	ContractID     int64                 `db:"contract_id" json:"contract_id"`
	RaisedBy       int64                 `db:"raised_by" json:"raised_by"`
	DisputeType    DisputeTypeEnum       `db:"dispute_type" json:"dispute_type"`
	Subject        string                `db:"subject" json:"subject"`
	Description    string                `db:"description" json:"description"`
	AmountDisputed pgtype.Numeric        `db:"amount_disputed" json:"amount_disputed"`
	Status         NullDisputeStatusEnum `db:"status" json:"status"`
	Resolution     pgtype.Text           `db:"resolution" json:"resolution"`
	ResolvedBy     pgtype.Int8           `db:"resolved_by" json:"resolved_by"`
	CreatedAt      pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
	ResolvedAt     pgtype.Timestamptz    `db:"resolved_at" json:"resolved_at"`
}

type Job struct {
	ID                 int64                   `db:"id" json:"id"`
	ClientID           int64                   `db:"client_id" json:"client_id"`
	CategoryID         pgtype.Int8             `db:"category_id" json:"category_id"`
	Title              string                  `db:"title" json:"title"`
	Description        string                  `db:"description" json:"description"`
	Requirements       pgtype.Text             `db:"requirements" json:"requirements"`
	BudgetType         BudgetTypeEnum          `db:"budget_type" json:"budget_type"`
	BudgetMin          pgtype.Numeric          `db:"budget_min" json:"budget_min"`
	BudgetMax          pgtype.Numeric          `db:"budget_max" json:"budget_max"`
	HourlyRateMin      pgtype.Numeric          `db:"hourly_rate_min" json:"hourly_rate_min"`
	HourlyRateMax      pgtype.Numeric          `db:"hourly_rate_max" json:"hourly_rate_max"`
	EstimatedHours     pgtype.Int4             `db:"estimated_hours" json:"estimated_hours"`
	ProjectDuration    NullProjectDurationEnum `db:"project_duration" json:"project_duration"`
	Urgency            NullUrgencyEnum         `db:"urgency" json:"urgency"`
	LocationType       LocationTypeEnum        `db:"location_type" json:"location_type"`
	JobAddress         pgtype.Text             `db:"job_address" json:"job_address"`
	City               pgtype.Text             `db:"city" json:"city"`
	State              pgtype.Text             `db:"state" json:"state"`
	ZipCode            pgtype.Text             `db:"zip_code" json:"zip_code"`
	Country            pgtype.Text             `db:"country" json:"country"`
	Latitude           pgtype.Numeric          `db:"latitude" json:"latitude"`
	Longitude          pgtype.Numeric          `db:"longitude" json:"longitude"`
	PreferredStartDate pgtype.Date             `db:"preferred_start_date" json:"preferred_start_date"`
	Deadline           pgtype.Date             `db:"deadline" json:"deadline"`
	Status             NullJobStatusEnum       `db:"status" json:"status"`
	Visibility         NullVisibilityEnum      `db:"visibility" json:"visibility"`
	ApplicationsCount  pgtype.Int4             `db:"applications_count" json:"applications_count"`
	ViewsCount         pgtype.Int4             `db:"views_count" json:"views_count"`
	IsFeatured         pgtype.Bool             `db:"is_featured" json:"is_featured"`
	CreatedAt          pgtype.Timestamptz      `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz      `db:"updated_at" json:"updated_at"`
	PublishedAt        pgtype.Timestamptz      `db:"published_at" json:"published_at"`
	ClosedAt           pgtype.Timestamptz      `db:"closed_at" json:"closed_at"`
}

type JobAttachment struct {
	ID         int64              `db:"id" json:"id"`
	JobID      int64              `db:"job_id" json:"job_id"`
	FileName   string             `db:"file_name" json:"file_name"`
	FilePath   string             `db:"file_path" json:"file_path"`
	FileSize   int32              `db:"file_size" json:"file_size"`
	FileType   pgtype.Text        `db:"file_type" json:"file_type"`
	UploadedBy int64              `db:"uploaded_by" json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type JobSkill struct {
	ID               int64                    `db:"id" json:"id"`
	JobID            int64                    `db:"job_id" json:"job_id"`
	SkillID          int64                    `db:"skill_id" json:"skill_id"`
	IsRequired       pgtype.Bool              `db:"is_required" json:"is_required"`
	ProficiencyLevel NullProficiencyLevelEnum `db:"proficiency_level" json:"proficiency_level"`
	CreatedAt        pgtype.Timestamptz       `db:"created_at" json:"created_at"`
}

type JobView struct {
	ID        int64              `db:"id" json:"id"`
	JobID     int64              `db:"job_id" json:"job_id"`
	UserID    pgtype.Int8        `db:"user_id" json:"user_id"`
	IpAddress pgtype.Text        `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text        `db:"user_agent" json:"user_agent"`
	ViewedAt  pgtype.Timestamptz `db:"viewed_at" json:"viewed_at"`
}

type Message struct {
	ID              int64               `db:"id" json:"id"`
	ContractID      pgtype.Int8         `db:"contract_id" json:"contract_id"`
	JobID           pgtype.Int8         `db:"job_id" json:"job_id"`
	SenderID        int64               `db:"sender_id" json:"sender_id"`
	RecipientID     int64               `db:"recipient_id" json:"recipient_id"`
	Subject         pgtype.Text         `db:"subject" json:"subject"`
	Message         string              `db:"message" json:"message"`
	MessageType     NullMessageTypeEnum `db:"message_type" json:"message_type"`
	IsRead          pgtype.Bool         `db:"is_read" json:"is_read"`
	ParentMessageID pgtype.Int8         `db:"parent_message_id" json:"parent_message_id"`
	CreatedAt       pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	ReadAt          pgtype.Timestamptz  `db:"read_at" json:"read_at"`
}

type MessageAttachment struct {
	ID        int64              `db:"id" json:"id"`
	MessageID int64              `db:"message_id" json:"message_id"`
	FileName  string             `db:"file_name" json:"file_name"`
	FilePath  string             `db:"file_path" json:"file_path"`
	FileSize  int32              `db:"file_size" json:"file_size"`
	FileType  pgtype.Text        `db:"file_type" json:"file_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Milestone struct {
	ID          int64                   `db:"id" json:"id"`
	ContractID  int64                   `db:"contract_id" json:"contract_id"`
	Title       string                  `db:"title" json:"title"`
	Description pgtype.Text             `db:"description" json:"description"`
	Amount      pgtype.Numeric          `db:"amount" json:"amount"`
	DueDate     pgtype.Date             `db:"due_date" json:"due_date"`
	Status      NullMilestoneStatusEnum `db:"status" json:"status"`
	OrderIndex  pgtype.Int4             `db:"order_index" json:"order_index"`
	CreatedAt   pgtype.Timestamptz      `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz      `db:"updated_at" json:"updated_at"`
	SubmittedAt pgtype.Timestamptz      `db:"submitted_at" json:"submitted_at"`
	ApprovedAt  pgtype.Timestamptz      `db:"approved_at" json:"approved_at"`
	PaidAt      pgtype.Timestamptz      `db:"paid_at" json:"paid_at"`
}

type Notification struct {
	ID                int64                `db:"id" json:"id"`
	UserID            int64                `db:"user_id" json:"user_id"`
	Title             string               `db:"title" json:"title"`
	Message           string               `db:"message" json:"message"`
	Type              NotificationTypeEnum `db:"type" json:"type"`
	RelatedEntityType pgtype.Text          `db:"related_entity_type" json:"related_entity_type"`
	RelatedEntityID   pgtype.Int8          `db:"related_entity_id" json:"related_entity_id"`
	IsRead            pgtype.Bool          `db:"is_read" json:"is_read"`
	IsEmailSent       pgtype.Bool          `db:"is_email_sent" json:"is_email_sent"`
	IsPushSent        pgtype.Bool          `db:"is_push_sent" json:"is_push_sent"`
	CreatedAt         pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	ReadAt            pgtype.Timestamptz   `db:"read_at" json:"read_at"`
}

type Proposal struct {
	ID                    int64                  `db:"id" json:"id"`
	JobID                 int64                  `db:"job_id" json:"job_id"`
	FreelancerID          int64                  `db:"freelancer_id" json:"freelancer_id"`
	CoverLetter           string                 `db:"cover_letter" json:"cover_letter"`
	ProposedRate          pgtype.Numeric         `db:"proposed_rate" json:"proposed_rate"`
	RateType              RateTypeEnum           `db:"rate_type" json:"rate_type"`
	EstimatedHours        pgtype.Int4            `db:"estimated_hours" json:"estimated_hours"`
	DeliveryTime          pgtype.Int4            `db:"delivery_time" json:"delivery_time"`
	AvailabilityStartDate pgtype.Date            `db:"availability_start_date" json:"availability_start_date"`
	Status                NullProposalStatusEnum `db:"status" json:"status"`
	IsFeatured            pgtype.Bool            `db:"is_featured" json:"is_featured"`
	CreatedAt             pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
	RespondedAt           pgtype.Timestamptz     `db:"responded_at" json:"responded_at"`
}

type ProposalAttachment struct {
	ID         int64              `db:"id" json:"id"`
	ProposalID int64              `db:"proposal_id" json:"proposal_id"`
	FileName   string             `db:"file_name" json:"file_name"`
	FilePath   string             `db:"file_path" json:"file_path"`
	FileSize   int32              `db:"file_size" json:"file_size"`
	FileType   pgtype.Text        `db:"file_type" json:"file_type"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Review struct {
	ID                    int64                `db:"id" json:"id"`
	ContractID            int64                `db:"contract_id" json:"contract_id"`
	ReviewerID            int64                `db:"reviewer_id" json:"reviewer_id"`
	RevieweeID            int64                `db:"reviewee_id" json:"reviewee_id"`
	Rating                int32                `db:"rating" json:"rating"`
	ReviewText            pgtype.Text          `db:"review_text" json:"review_text"`
	CommunicationRating   pgtype.Int4          `db:"communication_rating" json:"communication_rating"`
	QualityRating         pgtype.Int4          `db:"quality_rating" json:"quality_rating"`
	TimelinessRating      pgtype.Int4          `db:"timeliness_rating" json:"timeliness_rating"`
	ProfessionalismRating pgtype.Int4          `db:"professionalism_rating" json:"professionalism_rating"`
	WouldRecommend        pgtype.Bool          `db:"would_recommend" json:"would_recommend"`
	IsPublic              pgtype.Bool          `db:"is_public" json:"is_public"`
	Status                NullReviewStatusEnum `db:"status" json:"status"`
	CreatedAt             pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
}

type SavedJob struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	JobID     int64              `db:"job_id" json:"job_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Skill struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	CategoryID  pgtype.Int8        `db:"category_id" json:"category_id"`
	Description pgtype.Text        `db:"description" json:"description"`
	IsActive    pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TimeLog struct {
	ID           int64                 `db:"id" json:"id"`
	ContractID   int64                 `db:"contract_id" json:"contract_id"`
	FreelancerID int64                 `db:"freelancer_id" json:"freelancer_id"`
	Description  pgtype.Text           `db:"description" json:"description"`
	StartTime    pgtype.Timestamptz    `db:"start_time" json:"start_time"`
	EndTime      pgtype.Timestamptz    `db:"end_time" json:"end_time"`
	HoursLogged  pgtype.Numeric        `db:"hours_logged" json:"hours_logged"`
	HourlyRate   pgtype.Numeric        `db:"hourly_rate" json:"hourly_rate"`
	TotalAmount  pgtype.Numeric        `db:"total_amount" json:"total_amount"`
	Status       NullTimeLogStatusEnum `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
}

type Transaction struct {
	ID                   int64                     `db:"id" json:"id"`
	ContractID           pgtype.Int8               `db:"contract_id" json:"contract_id"`
	MilestoneID          pgtype.Int8               `db:"milestone_id" json:"milestone_id"`
	PayerID              int64                     `db:"payer_id" json:"payer_id"`
	PayeeID              int64                     `db:"payee_id" json:"payee_id"`
	Amount               pgtype.Numeric            `db:"amount" json:"amount"`
	PlatformFee          pgtype.Numeric            `db:"platform_fee" json:"platform_fee"`
	NetAmount            pgtype.Numeric            `db:"net_amount" json:"net_amount"`
	TransactionType      NullTransactionTypeEnum   `db:"transaction_type" json:"transaction_type"`
	PaymentMethod        PaymentMethodEnum         `db:"payment_method" json:"payment_method"`
	PaymentGateway       pgtype.Text               `db:"payment_gateway" json:"payment_gateway"`
	GatewayTransactionID pgtype.Text               `db:"gateway_transaction_id" json:"gateway_transaction_id"`
	Status               NullTransactionStatusEnum `db:"status" json:"status"`
	Description          pgtype.Text               `db:"description" json:"description"`
	CreatedAt            pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz        `db:"updated_at" json:"updated_at"`
	ProcessedAt          pgtype.Timestamptz        `db:"processed_at" json:"processed_at"`
}

type User struct {
	ID              int64              `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	PasswordHash    string             `db:"password_hash" json:"password_hash"`
	FirstName       string             `db:"first_name" json:"first_name"`
	LastName        string             `db:"last_name" json:"last_name"`
	Phone           pgtype.Text        `db:"phone" json:"phone"`
	ProfileImageUrl pgtype.Text        `db:"profile_image_url" json:"profile_image_url"`
	UserType        UserTypeEnum       `db:"user_type" json:"user_type"`
	IsVerified      pgtype.Bool        `db:"is_verified" json:"is_verified"`
	EmailVerified   pgtype.Bool        `db:"email_verified" json:"email_verified"`
	PhoneVerified   pgtype.Bool        `db:"phone_verified" json:"phone_verified"`
	Status          NullStatusEnum     `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastLogin       pgtype.Timestamptz `db:"last_login" json:"last_login"`
	Timezone        pgtype.Text        `db:"timezone" json:"timezone"`
}

type UserNotificationSetting struct {
	ID                    int64              `db:"id" json:"id"`
	UserID                int64              `db:"user_id" json:"user_id"`
	EmailJobPosted        pgtype.Bool        `db:"email_job_posted" json:"email_job_posted"`
	EmailProposalReceived pgtype.Bool        `db:"email_proposal_received" json:"email_proposal_received"`
	EmailProposalStatus   pgtype.Bool        `db:"email_proposal_status" json:"email_proposal_status"`
	EmailContractUpdates  pgtype.Bool        `db:"email_contract_updates" json:"email_contract_updates"`
	EmailPaymentUpdates   pgtype.Bool        `db:"email_payment_updates" json:"email_payment_updates"`
	EmailMessages         pgtype.Bool        `db:"email_messages" json:"email_messages"`
	EmailReviews          pgtype.Bool        `db:"email_reviews" json:"email_reviews"`
	PushJobPosted         pgtype.Bool        `db:"push_job_posted" json:"push_job_posted"`
	PushProposalReceived  pgtype.Bool        `db:"push_proposal_received" json:"push_proposal_received"`
	PushProposalStatus    pgtype.Bool        `db:"push_proposal_status" json:"push_proposal_status"`
	PushContractUpdates   pgtype.Bool        `db:"push_contract_updates" json:"push_contract_updates"`
	PushPaymentUpdates    pgtype.Bool        `db:"push_payment_updates" json:"push_payment_updates"`
	PushMessages          pgtype.Bool        `db:"push_messages" json:"push_messages"`
	PushReviews           pgtype.Bool        `db:"push_reviews" json:"push_reviews"`
	SmsImportantUpdates   pgtype.Bool        `db:"sms_important_updates" json:"sms_important_updates"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserPortfolio struct {
	ID             int64              `db:"id" json:"id"`
	UserID         int64              `db:"user_id" json:"user_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	ProjectUrl     pgtype.Text        `db:"project_url" json:"project_url"`
	ImageUrl       pgtype.Text        `db:"image_url" json:"image_url"`
	CompletionDate pgtype.Date        `db:"completion_date" json:"completion_date"`
	Skills         []byte             `db:"skills" json:"skills"`
	IsFeatured     pgtype.Bool        `db:"is_featured" json:"is_featured"`
	SortOrder      pgtype.Int4        `db:"sort_order" json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserProfile struct {
	ID              int64                   `db:"id" json:"id"`
	UserID          int64                   `db:"user_id" json:"user_id"`
	Bio             pgtype.Text             `db:"bio" json:"bio"`
	HourlyRate      pgtype.Numeric          `db:"hourly_rate" json:"hourly_rate"`
	ExperienceLevel NullExperienceLevelEnum `db:"experience_level" json:"experience_level"`
	Availability    NullAvailabilityEnum    `db:"availability" json:"availability"`
	LocationAddress pgtype.Text             `db:"location_address" json:"location_address"`
	City            pgtype.Text             `db:"city" json:"city"`
	State           pgtype.Text             `db:"state" json:"state"`
	ZipCode         pgtype.Text             `db:"zip_code" json:"zip_code"`
	Country         pgtype.Text             `db:"country" json:"country"`
	Latitude        pgtype.Numeric          `db:"latitude" json:"latitude"`
	Longitude       pgtype.Numeric          `db:"longitude" json:"longitude"`
	ServiceRadius   pgtype.Int4             `db:"service_radius" json:"service_radius"`
	Languages       []byte                  `db:"languages" json:"languages"`
	WebsiteUrl      pgtype.Text             `db:"website_url" json:"website_url"`
	LinkedinUrl     pgtype.Text             `db:"linkedin_url" json:"linkedin_url"`
	FacebookUrl     pgtype.Text             `db:"facebook_url" json:"facebook_url"`
	InstagramUrl    pgtype.Text             `db:"instagram_url" json:"instagram_url"`
	CreatedAt       pgtype.Timestamptz      `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz      `db:"updated_at" json:"updated_at"`
}

type UserSkill struct {
	ID                int64                    `db:"id" json:"id"`
	UserID            int64                    `db:"user_id" json:"user_id"`
	SkillID           int64                    `db:"skill_id" json:"skill_id"`
	ProficiencyLevel  NullProficiencyLevelEnum `db:"proficiency_level" json:"proficiency_level"`
	YearsOfExperience pgtype.Int4              `db:"years_of_experience" json:"years_of_experience"`
	CreatedAt         pgtype.Timestamptz       `db:"created_at" json:"created_at"`
}

type UserWallet struct {
	ID             int64              `db:"id" json:"id"`
	UserID         int64              `db:"user_id" json:"user_id"`
	Balance        pgtype.Numeric     `db:"balance" json:"balance"`
	PendingBalance pgtype.Numeric     `db:"pending_balance" json:"pending_balance"`
	TotalEarned    pgtype.Numeric     `db:"total_earned" json:"total_earned"`
	TotalSpent     pgtype.Numeric     `db:"total_spent" json:"total_spent"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
